version: "3.8"

services:
  nginx_server:
   build:
     context: ./nginx
   image: nginx
   container_name: "nginx_cont"
   ports:
    - "80:80"
   networks:
    - django
   depends_on:
     - django_app
   restart: always
  
  django_app:
   build:
     context: .
   image: django_app
   container_name: django_nitin
   ports:
    - "8000:8000"
   command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
   networks:
     - django
   depends_on:
    - db
   env_file:
    - ".env"  
   restart: always
   healthcheck:
     test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
     interval: 10s
     timeout: 5s
     retries: 5
     start_period: 60s    
  db:
   image: mysql
   container_name: db_conts
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: text_db   
   networks:
    - django
   volumes:
    - django-volume:/var/lib/mysql
   restart: always
   healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
networks:
  django:
volumes:
  django-volume:
